In [1]:

# Step 1: Data Collection

!pip -q install ucimlrepo

from ucimlrepo import fetch_ucirepo
import pandas as pd

# Download the official UCI Heart Disease dataset
heart_disease = fetch_ucirepo(id=45)

# Combine the features and target into one DataFrame
X = heart_disease.data.features
y = heart_disease.data.targets

df = pd.concat([X, y], axis=1)

print("Dataset downloaded successfully!")
print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

display(df.head())

Dataset downloaded successfully!
Dataset shape: (303, 14)

Column names:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num']

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63,1,1,145,233,1,2,150,0,2.3,3,0.0,6.0,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2
2,67,1,4,120,229,0,2,129,1,2.6,2,2.0,7.0,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0.0,3.0,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,3.0,0

In [2]:
# Step 2: Data Understanding

print("Dataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

print("\nStatistical Summary:")
display(df.describe())

print("\nTarget Distribution:")
print(df["num"].value_counts().sort_index())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        299 non-null    float64
 12  thal      301 non-null    float64
 13  num       303 non-null    int64
dtypes: float64(3), int64(11)
memory usage: 33.3 KB

Missing Values:
age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          4
thal        2
num         0
dtype: int64

Statistical Summary:

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,299.000000,301.000000,303.000000
mean,54.438944,0.679868,3.158416,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.672241,4.734219,0.937294
std,9.038662,0.467299,0.960126,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,0.937438,1.939706,1.228536
min,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000,3.000000,0.000000
25%,48.000000,0.000000,3.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,3.000000,0.000000
50%,56.000000,1.000000,3.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000,3.000000,0.000000
75%,61.000000,1.000000,4.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,1.000000,7.000000,2.000000
max,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000,7.000000,4.000000

Target Distribution:
num
0    164
1     55
2     36
3     35
4     13
Name: count, dtype: int64

In [3]:

# Step 3: Data Preprocessing and Label Encoding

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Select exactly four input attributes
selected_features = ["age", "sex", "cp", "thalach"]

# Create a new dataset with only the selected features and target
processed_df = df[selected_features + ["num"]].copy()

# Convert the original target into two classes:
# 0 = No heart disease
# 1 = Heart disease present
processed_df["target"] = (processed_df["num"] > 0).astype(int)

# Remove the original five-class target
processed_df.drop(columns=["num"], inplace=True)

# Encode the target labels
label_encoder = LabelEncoder()
processed_df["target"] = label_encoder.fit_transform(
    processed_df["target"]
)

print("Selected input attributes:", selected_features)
print("\nMissing values after selection:")
print(processed_df.isnull().sum())

print("\nProcessed dataset shape:", processed_df.shape)
print("\nTarget distribution:")
print(processed_df["target"].value_counts())

display(processed_df.head())

Selected input attributes: ['age', 'sex', 'cp', 'thalach']

Missing values after selection:
age        0
sex        0
cp         0
thalach    0
target     0
dtype: int64

Processed dataset shape: (303, 5)

Target distribution:
target
0    164
1    139
Name: count, dtype: int64

   age  sex  cp  thalach  target
0   63    1   1      150       0
1   67    1   4      108       1
2   67    1   4      129       1
3   37    1   3      187       0
4   41    0   2      172       0

In [4]:

# Step 4.1: Split the data into training and testing sets

from sklearn.model_selection import train_test_split

X = processed_df[["age", "sex", "cp", "thalach"]]
y = processed_df["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))
print("Training features:", X_train.shape[1])

Training samples: 242
Testing samples: 61
Training features: 4

In [5]:

# Step 4.2: Scale features and train the SVC model

from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

# Fit the scaler only on training data to avoid data leakage
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train the Support Vector Classifier
model = SVC(kernel="rbf", random_state=42)

model.fit(X_train_scaled, y_train)

print("SVC model trained successfully!")
print("Model input features:", X_train.shape[1])

SVC model trained successfully!
Model input features: 4

In [6]:

# Step 4.3: Evaluate model performance

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

y_pred = model.predict(X_test_scaled)

print("Accuracy:", round(accuracy_score(y_test, y_pred) * 100, 2), "%")

print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 78.69 %

Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.85      0.81        33
           1       0.80      0.71      0.75        28

    accuracy                           0.79        61
   macro avg       0.79      0.78      0.78        61
weighted avg       0.79      0.79      0.79        61

Confusion Matrix:
[[28  5]
 [ 8 20]]

In [7]:

# Step 5: Save the model and scaler for deployment

import joblib

joblib.dump(model, "heart_disease_svc.pkl")
joblib.dump(scaler, "heart_disease_scaler.pkl")

print("Saved: heart_disease_svc.pkl")
print("Saved: heart_disease_scaler.pkl")

Saved: heart_disease_svc.pkl
Saved: heart_disease_scaler.pkl

In [8]:

from sklearn.model_selection import train_test_split

X = processed_df[["age", "sex", "cp", "thalach"]]
y = processed_df["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))
print("Training features:", X_train.shape[1])

Training samples: 242
Testing samples: 61
Training features: 4

In [9]:

from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

# Scale the input features
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create and train the SVC model
model = SVC(kernel="rbf", random_state=42)
model.fit(X_train_scaled, y_train)

print("SVC model trained successfully!")
print("Model input features:", X_train.shape[1])

SVC model trained successfully!
Model input features: 4

In [10]:

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# Make predictions on the testing data
y_pred = model.predict(X_test_scaled)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", round(accuracy * 100, 2), "%")

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=["No Heart Disease", "Heart Disease"],
    zero_division=0
))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Model Accuracy: 78.69 %

Classification Report:
                  precision    recall  f1-score   support

No Heart Disease       0.78      0.85      0.81        33
   Heart Disease       0.80      0.71      0.75        28

        accuracy                           0.79        61
       macro avg       0.79      0.78      0.78        61
    weighted avg       0.79      0.79      0.79        61

Confusion Matrix:
[[28  5]
 [ 8 20]]

In [11]:

import joblib

# Save the trained SVC model
joblib.dump(model, "heart_disease_svc.pkl")

# Save the fitted scaler
joblib.dump(scaler, "heart_disease_scaler.pkl")

print("Model saved: heart_disease_svc.pkl")
print("Scaler saved: heart_disease_scaler.pkl")

Model saved: heart_disease_svc.pkl
Scaler saved: heart_disease_scaler.pkl